### ISSUE TITLE
Fabric is undefined in test environment

### ISSUE THREAD

**Issue by yashikagarg13** [nhn/tui.image-editor#134]
## Version
3.3.0

## Development Environment
Browser: Chrome
OS: MacOS

## Current Behavior

Getting below error message when writing a test for an ES6 module requiring 'tui-image-editor'.
```js
TypeError: Cannot read property 'createClass' of undefined
```
Using Jest for writing tests

## Expected Behavior
It should not raise above error

**Comment by junghwan-park** [comment]
@yashikagarg13 
Can you describe example code of your T/C and Jest environment settings?

**Comment by yashikagarg13** [comment]
Example Code:

App.js
```
const ImageEditor = require('tui-image-editor')

export default class App {
    render () {
        return 'Hello World'
    }
}
```

App.test.js
```
import App from './App'
import {shallow} from 'enzyme'
import toJson from 'enzyme-to-json'

describe('App', () => {
   it('should render correctly', () => {
      let wrapper = shallow(<Dashboard />, store)
      expect(toJson(wrapper)).toMatchSnapshot()
   })
})
```

Application created using `react-scripts@1.1.4`. It is failing at import itself. `const ImageEditor = require('tui-image-editor')` giving error `Cannot read property 'createClass' of undefined`

**Comment by yashikagarg13** [comment]
@junghwan-park anything about this?

**Comment by junghwan-park** [comment]
@yashikagarg13 
Please add `fabric@1.x.x(1.6.7 or higher)`  your package dependency. TOAST UI Image Editor install `fabric@1.6.7` in their package directory's `node_modules` initially by `npm install --no-option --no-save fabric@1.6.7`.
If you execute`npm install` after **tui-image-editor** installed, the `tui-image-editor/node_modules/fabric/fabric.require.js` is deleted by npm.

Sorry for your inconvenience.

**Comment by yashikagarg13** [comment]
@junghwan-park I have `fabric` installed as you mentioned
<img width="317" alt="screenshot 2019-02-18 at 11 48 23 am" src="https://user-images.githubusercontent.com/11815050/52931726-688f7b00-3373-11e9-95cf-9abc78dac964.png">
But I am still getting the error. Its a blocker for my team to use the library as because of this all test files are failing. We will really appreciate if you could help.

**Comment by Olgagr** [comment]
I have the same problem. I have fabric installed (in the package.json I have postInstall)

```
"postInstall": "npm install --no-save --no-optional fabric@^1.6.7"
```

And when I require the ImageEditor:

```
const ImageEditor = require('tui-image-editor')
```

I get an error:

```﻿
/home/test/Docume…age-editor.js:12869 Uncaught TypeError: Cannot read property 'createClass' of undefined
```
The error leads to this line:

```
var Cropzone = _fabric2.default.util.createClass(_fabric2.default.Rect
```

Does nobody else has this error?

**Comment by arggh** [comment]
> Does nobody else has this error?

Yes. Just tried to take this library for a spin, like so:

```
npm install --save tui-image-editor
```

```js
// app.js

import ImageEditor from 'tui-image-editor';
```
⬇︎
```
Promise not resolved TypeError: Cannot read property 'createClass' of undefined
    at Object.eval (/node_modules/tui-image-editor/dist/tui-image-editor.js:12877)
    at __webpack_require__ (/node_modules/tui-image-editor/dist/tui-image-editor.js:44)
    at Object.eval (/node_modules/tui-image-editor/dist/tui-image-editor.js:12399)
    at __webpack_require__ (/node_modules/tui-image-editor/dist/tui-image-editor.js:44)
    at Object.eval (/node_modules/tui-image-editor/dist/tui-image-editor.js:10681)
    at __webpack_require__ (/node_modules/tui-image-editor/dist/tui-image-editor.js:44)
    at Object.eval (/node_modules/tui-image-editor/dist/tui-image-editor.js:628)
    at __webpack_require__ (/node_modules/tui-image-editor/dist/tui-image-editor.js:44)
    at Object.eval (/node_modules/tui-image-editor/dist/tui-image-editor.js:75)
    at __webpack_require__ (/node_modules/tui-image-editor/dist/tui-image-editor.js:44)
```

**Comment by GraemeFulton** [comment]
has anyone fixed this? I'm getting it in my react app. I have included  fabric@^1.6.7, and imported it before tui-image-editor, and still get the error

**Comment by GraemeFulton** [comment]
if anyone is still struggling with this, I managed to get it working by creating a new `tui-image-editor.js`, and pasting the fabric.js code above it, so it looks like this:

<img width="300" alt="Screenshot 2019-08-01 at 09 47 54" src="https://user-images.githubusercontent.com/4354786/62279314-bee40800-b441-11e9-960d-b0f1198e484a.png">

Next, I replaced every mention of `_fabric2.default` with `fabric`, so that it's using the main fabric variable from the top of the file.

Finally, I declared a global ImageEditor before the tui code begins. This can also be bound to the window, `window.ImageEditor = ImageEditor`, so you can then access an ImageEditor with fabric guaranteed anywhere in your app using `window.ImageEditor`.

I have no idea why fabric wouldn't work for me, but that's how i forced it.

**Comment by GraemeFulton** [comment]
No idea why fabric would never work, but I made a workaround:

I created a new `image_tui.min.js` for Froala, and pasted the `fabric.js` and `tui-image-editor.js` code above it the regular `image_tui.min.js` code, so the top looks like this:

<img width="300" alt="Screenshot 2019-08-01 at 09 47 54" src="https://user-images.githubusercontent.com/4354786/62279314-bee40800-b441-11e9-960d-b0f1198e484a.png">

Next, I replaced every mention of `_fabric2.default` with `fabric`, so that it's using the main fabric variable from the top of the file.

Finally, I declared a global ImageEditor before the tui code begins. Then, I added this line:

` window.tui = _imageEditor2`, just underneath `module.exports = _imageEditor2.default;`. That makes the tui ImageEditor available to the froala plugin code at the bottom. Here is the full code:

https://gist.github.com/GraemeFulton/5dd8c9bd3c6dff43b1690718a4297845

I have no idea why fabric wouldn't work for me, but that's how i forced it to
