### ISSUE TITLE
Interacting with the Editor on mobile scrolls the Page

### ISSUE THREAD

**Issue by karatektus** [nhn/tui.image-editor#150]
## Version
3.5.0
## Development Environment
Windows - iOS

## Current Behavior
When interacting with the editor on a touch device, it scrolls the Page

## Expected Behavior
The page should not move while drawing/selecting etc.

Example: http://nhnent.github.io/tui.image-editor/latest/tutorial-example03-mobile.html

**Comment by jinwoo-kim-nhn** [comment]
@karatektus thanks.
I tested it as below and it seems to be no problem.

![2019-02-21 6 22 17](https://user-images.githubusercontent.com/35218826/53158340-b40d8780-3606-11e9-91c0-e65197c755ca.png)

The example page is scrolled because it is wrapped in a layout with a left menu for the introduction of the editor.

The example page is just an example using api, and we expect the end user to be able to use the example to create a much more valuable UI.
