### ISSUE TITLE
How can i disable delete key default action?

### ISSUE THREAD

**Issue by haki9** [nhn/tui.image-editor#178]
## Version
v3.5.2

I have an Input tag and when I edit default value with delete keyboard, it also delete active Object.

**Comment by junghwan-park** [comment]
@haki9 There is no way to disable delete key default action yet. Temporally using `imageEditor.discardSelection();` [API](http://nhn.github.io/tui.image-editor/latest/ImageEditor#discardSelection) for prevent active object from deleting.

ImageEditor listen `window`'s keydown event because of undo, redo, delete feature. I think it has to be enhanced somehow. I'll add keydown events to enhancement list. Thanks.
