### ISSUE TITLE
Can't edit (but can see) images from cross domains

### ISSUE THREAD

**Issue by roytz** [nhn/tui.image-editor#207]
## Version
3.5.2

## Development Environment
MacOS Mojave
Node.js 10.14.0
React 16.8.6

## Current Behavior
When using [image href](https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png) of cross domains - I get a _"No 'Access-Control-Allow-Origin' header is present on the requested resource"_ error.
I can see the image (using froala) before opening the TUI advanced-editor, but when opening the advanced editor I get the _"No 'Access-Control-Allow-Origin' header is present on the requested resource"_ error and therefore can't see (inside the advanced-editor) nor edit the image.

![can see the image before opening advanced-edit](https://user-images.githubusercontent.com/16700423/58425823-da5d1c00-8068-11e9-900f-5c7298a9368b.png)

![error when opening advanced-edit](https://user-images.githubusercontent.com/16700423/58425900-12645f00-8069-11e9-8b75-14c385cc9bd8.png)

## Expected Behavior
Being able to see and edit cross-domains images in TUI advanced editor

**Comment by shai32** [comment]
The same issue happens to me with this file:
https://s3-eu-west-1.amazonaws.com/gf.red.kfdabazdsxc4yyts9.files/froalaFiles1559127824542-flowerofthemonthclub.jpg
from origin:
https://backoffice.general.red.gefen-qa.online

although the s3 is configured property with cross-origin enabled to all domains (with<AllowedOrigin>*</AllowedOrigin>)

also, I executed on terminal: 
`curl -H "origin: https://backoffice.general.red.gefen-qa.online" -v "https://s3-eu-west-1.amazonaws.com/gf.red.kfdabazdsxc4yyts9.files/froalaFiles1559127824542-flowerofthemonthclub.jpg"` 
and the file was retrieved ok with no error
so the problem is not in the server

**Comment by roytz** [comment]
After talking to Froala's support team, they also suggested it's related to TAU.
Here's a reproduction of the bug -  https://jsfiddle.net/e2b5xyf8/14/

**Comment by romanfedyshyn** [comment]
Hi, @jinwoo-kim-nhn do you have any suggestions for what it could be?

**Comment by romanfedyshyn** [comment]
@seonim-ryu maybe you can help here?

**Comment by romanfedyshyn** [comment]
@junghwan-park any updates?

**Comment by romanfedyshyn** [comment]
@seonim-ryu @junghwan-park hello guys, are you going to do something with it?

**Comment by junghwan-park** [comment]
@romanfedyshyn Sorry for the late reply.
I think I can resolve loading a cross origin image. But, get imageData from tainted canvas(cross origin image has drawn) is needs to researching.
First, I'll add `crossOrigin` option for loaded image.

**Comment by romanfedyshyn** [comment]
> @romanfedyshyn Sorry for the late reply.
> I think I can resolve loading a cross origin image. But, get imageData from tainted canvas(cross origin image has drawn) is needs to researching.
> First, I'll add `crossOrigin` option for loaded image.

Hi, just want to ask if you do something with that?

**Comment by pegasus1982** [comment]
I have same issue.
How can I solve it?
