### ISSUE TITLE
Use api direct (basic) is not working on internet explorer 11

### ISSUE THREAD

**Issue by shadabahmad11** [nhn/tui.image-editor#218]
## Version 
v3.6.0

## Development Environment
OS: Window 10, 
Browser: Internet Explorer 11 and Safari 5.1.7(window 10)

## Current Behavior
Image is not loading in internet explorer 11
Page is not loading on window safari.
http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect
http://13.234.119.145/tui.image-editor-production/examples/example02-useApiDirect.html

```js
var imageEditor = new tui.ImageEditor('.tui-image-editor', {
    cssMaxWidth: 700,
    cssMaxHeight: 500,
    selectionStyle: {
        cornerSize: 20,
        rotatingPointOffset: 70
    }
});
I think variable imageEditor is not working.
```

## Expected Behavior
Image should load. I should be able to edit image.

**Comment by guillaumegarcia13** [comment]
If you load the example outside ot its iframe: https://nhn.github.io/tui.image-editor/latest/examples/example01-includeUi.html, I assume that is works, right?

The example you are referring to (http://nhn.github.io/tui.image-editor/latest/examples/example02-useApiDirect.html) has a service-basic.js  file which is not compatible with IE because of unsupported Template literals: https://caniuse.com/#feat=template-literals.

**Comment by junghwan-park** [comment]
@shadabahmad11 Oh, I'll change ES6 syntax to ES5. Thank you for your report.
