### ISSUE TITLE
Unable to edit text field

### ISSUE THREAD

**Issue by lightway82** [nhn/tui.image-editor#354]
## Version
3.8.0

## Development Environment
I open the editor in bootstrap 4 modal window.
Tested in Opera and Chrome.

## Current Behavior
I insert text in editor, but i can't edit text. Input by keyboard not working.
There are no errors in the console.

**Text editor function works good when it’s built in the page, however, in a modal window it doesn’t work**

![image](https://user-images.githubusercontent.com/17110240/76008095-22766c80-5f20-11ea-8b06-c90dd8a13767.png)

```js
 let imageEditor = new tui.ImageEditor('.imageEditor', {
              includeUI: {
                loadImage: {
                  path: URL.createObjectURL(file.data),
                  name: file.data.name
                },
                theme: blackTheme, // or whiteTheme

                menuBarPosition: 'left'
              },
              cssMaxWidth: 1024,
              cssMaxHeight: 768,
              usageStatistics: false
            });
```

**Comment by jeromeheissler** [comment]
Have you seen this : https://github.com/fabricjs/fabric.js/issues/3695#issuecomment-353360365

**Comment by superstar1128** [comment]
I can see same issue.
There are 2 way to fix issue.
- First, I removed focus eventListener from jquery.
- Second, I modified fabric.js library regarding https://github.com/fabricjs/fabric.js/issues/3695.

But I think both are not good solutions. I think it should be fixed with tui-image-editor.

**Comment by vsvanshi** [comment]
Anyone stumbling upon this issue who is also using Material -UI library and trying to show the Image Editor in a Dialog Component, you can pass the prop `disableEnforceFocus` to the dialog Root and it will work

**Comment by Keepcase** [comment]
@jinwoo-kim-nhn, @lja1018, are there any plans to make this worker better in tui-image-editor?

We also use this library with Material-UI within a Dialog Component and we had to resort to `disableEnforceFocus` (thanks @vsvanshi !) but according to their [docs](https://material-ui.com/api/modal/#props) it affects accessibility.

> If true, the modal will not prevent focus from leaving the modal while open.
Generally this should never be set to true as it makes the modal less accessible to assistive technologies, like screen readers.

**Comment by ericorruption** [comment]
For anyone with the same problem using React Bootstrap modal, `enforceFocus` solves the problem - at the expense of reduced accessibility. 
cc @lightway82

**Comment by dominikstraessle** [comment]
If you have this problem using Vuetify with the v-dialog component, you have to set the `retain-focus`-option to `false`. See https://vuetifyjs.com/en/api/v-dialog/#props.

Example:
```html
<v-dialog
      fullscreen
      persistent
      :retain-focus="false"
    >
```

**Comment by reggi49** [comment]
> For anyone with the same problem using React Bootstrap modal, `enforceFocus` solves the problem - at the expense of reduced accessibility. cc @lightway82

additional information, you can set enforceFocus to false. like the code below
`<Modal enforceFocus={false}>`

**Comment by fjwong** [comment]
Hello, we recently ran into this issue as well. We have a Vue.js app based on [Quasar 2.0](https://quasar.dev/), and we open the image editor in a [q-dialog component](https://quasar.dev/vue-components/dialog). We are using tui-image-editor v3.15.2.

Like in previous comments, this seems to be fixable by not allowing the dialog to refocus on itself when it loses focus, which can be done by putting it into [seamless](https://quasar.dev/vue-components/dialog#example--seamless) mode. Unfortunately, this doesn't work well for our application since it allows users to interact with the rest of the app while the dialog is open.

After a few days of trying to deal with this issue, we discovered that the original problem was in Fabric.js, and changes were made a few months ago in order to allow developers to address this (https://github.com/fabricjs/fabric.js/commit/9425064c6600f83f4258ab143a69efcfb3ad8a50). 

If anyone is interested, the following hacky workaround seems to work well for our case:

```javascript
const textareaContainer = ... // Reference to some html element inside of the modal dialog
const editorInstance = ... // Tui Image Editor instance
const graphics = editorInstance._graphics;
const canvas = graphics._canvas; // Fabric.js canvas
const { onObjectAdded } = graphics._handler;

// Detach default 'object:added' listener and replace it with our own
canvas.off('object:added', onObjectAdded);
canvas.on('object:added', (event: any) => {
  const { target } = event;
  if (target.type === 'i-text') {
    // A new text object was added
    target.hiddenTextareaContainer = textareaContainer;
  }
  onObjectAdded(event);
});
```

@jinwoo-kim-nhn @lja1018 I hope you do not mind me asking, but would it be possible to have a setting in the image editor that allows developers to set this `hiddenTextareaContainer` property in IText objects after these are created? (https://github.com/nhn/tui.image-editor/blob/master/apps/image-editor/src/js/component/text.js#L211)

**Comment by lja1018** [comment]
@fjwong 
I'm not sure but try the API `setObjectProperties`.

**Comment by fjwong** [comment]
@lja1018 Thanks a lot for the response.

We just tried `setObjectProperties` and it seems to partially work (`setObjectPropertiesQuietly` actually, otherwise the container element change gets recorded in the undo stack).

The problem we have is that, when users add a text element (which auto-selects it and makes it editable by default) the text is not initially editable. Deselecting and selecting the text object again makes it editable in this case.

That said, your suggestion made us do some additional investigation into how the text component works, and found that the following appears to work for our case:

```javascript
const textareaContainer = ... // Reference to some html element inside of the modal dialog
const editorInstance = ... // Tui Image Editor instance
editorInstance.on('addText', ({ originPosition }) => {
  editorInstance.addText('Initial text', {
    position: originPosition,
    styles: {
      ...
      hiddenTextareaContainer: textareaContainer,
    },
  });
});
```

Perhaps it would be a good idea to mention in [the docs](https://nhn.github.io/tui.image-editor/latest/ImageEditor#addText) that the `styles` option supports all members available to [IText objects](http://fabricjs.com/docs/fabric.IText.html).

Thanks a lot once more. :)

**Comment by mr-asaidi** [comment]
> For anyone with the same problem using React Bootstrap modal, `enforceFocus` solves the problem - at the expense of reduced accessibility.

@ericorruption, Thanks a lot for the inspiration, 

When using BootstrapVue modal, there are two props can be used to fix this behaviour
Either
ignore-enforce-focus-selector="..."
or 
no-enforce-focus

Again, at the expense of reduced accessibility
Check [Keyboard Navigation](https://bootstrap-vue.org/docs/components/modal#keyboard-navigation)

**Comment by jroyantor** [comment]
In bootstrap modal setting the '**data-bs-focus**' to **false** seems to be working. Like below:

`<div class="modal fade " id="showModal" tabindex="-1" data-bs-focus="false" role="dialog" aria-labelledby="showModalCenterTitle" aria-hidden="true">`
